version: '3.9'
services:
  pgserver-for-limit-control:
    container_name: pgserver-for-limit-control
    image: postgres
    networks:
      - network-1
    ports:
      - "5555:5432"
    depends_on:
      jenkins:
        condition: service_started
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: limit_microservice
      POSTGRES_PASSWORD: root
  limit-control:
    container_name: limit-control
    image: limit-control
    networks:
      - network-1
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      pgserver-for-limit-control:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgserver-for-limit-control:5432/limit_microservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - APP_ID=${APP_ID}
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
      - network-1
    ports:
      - "8081:8080" # Порт Jenkins
      - "50000:50000" # Для подключения агентов
    volumes:
      - jenkins_home:/var/jenkins_home # Для сохранения данных Jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Для использования Docker из Jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Отключение мастера установки
networks:
  network-1:

volumes:
  pg_data:
  jenkins_home:

